version: '3'
services:

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - local

networks:
  local:
    driver: bridge
